services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    volumes:
      - n8n_data:/home/node/.n8n
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`za.zolbooo.xyz`)
  traefik:
    image: traefik:v3.3
    restart: always
    container_name: traefik
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.traefik.acme.json:/acme.json"
    secrets:
      - htpasswd
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --certificatesresolvers.le.acme.email=hello+zol-alliance@zolbooo.xyz
      - --certificatesresolvers.le.acme.storage=acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asdefault=true
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=le
      - --entrypoints.websecure.http3.advertisedPort=443
    labels:
      - traefik.http.middlewares.auth.basicauth.usersfile=/run/secrets/htpasswd
  watchtower:
    image: containrrr/watchtower
    restart: always
    container_name: watchtower
    command: --interval 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  n8n_data:
secrets:
  htpasswd:
    file: traefik.htpasswd
