---
- name: Install Docker
  hosts: all
  tasks:
    - name: Check if Docker Compose is available
      command: docker compose version
      register: docker_compose_check
      failed_when: false
      changed_when: false
    - name: Install Docker
      include_role:
        name: ubuntu-install-docker
      when: docker_compose_check.rc != 0
